#!/bin/bash

export DOCTOSQL_RDBMS='{"userName":"sa", "password":"reallyStrongPwd123", "server":"localhost", "database":"develop"}'

tsc && node --unhandled-rejections=strict src/index -t descs >descs.txt 2>descs.sql
