#!/bin/bash

export DOCTOSQL_RDBMS='{"userName":"sa", "password":"reallyStrongPwd123", "server":"localhost", "database":"develop"}'

tsc && node src/index -t search -s "${1}" > "${1}_eq.txt" 2> "${1}_eq.sql"
